export const P = {
  ADMINISTRATOR: 1n << 0n,
  CONFIGURE_SERVER: 1n << 1n,
  CONFIGURE_CHANNELS: 1n << 2n,
  CONFIGURE_ROLES: 1n << 3n,
  KICK: 1n << 4n,
  BAN: 1n << 5n,
  UNBAN: 1n << 6n,
  GENERATE_INVITE: 1n << 7n,
  VIEW_CHANNEL: 1n << 8n,
  READ_MESSAGES: 1n << 9n,
  POST_MESSAGES: 1n << 10n,
  VIEW_HISTORY: 1n << 11n,
  MODERATE_MESSAGES: 1n << 12n,
  UPLOAD: 1n << 13n,
  REACT: 1n << 14n,
  NOTIFY_ALL: 1n << 15n,
  JOIN_VOICE: 1n << 16n,
  SPEAK: 1n << 17n,
  SILENCE: 1n << 18n,
  DEAFEN: 1n << 19n,
} as const;
